modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
    modId="boblib"
    version="0.2.0"
    displayName="BobLib"
    updateJSONURL="https://minecraft.darkboy.ru/api/check-mod-updates/boblib.json"
    displayURL="https://minecraft.darkboy.ru/mods/boblib"
    credits="Library for Bobsans mods"
    authors="Bobsans"
    description='''Provides functionality for use in Bobsans mods'''

    [[dependencies.boblib]]
        modId="forge"
        mandatory=true
        versionRange="[36,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.boblib]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5,1.17)"
        ordering="NONE"
        side="BOTH"
