modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
    modId="boblib"
    version="0.3.0"
    displayName="BobLib"
    updateJSONURL="https://minecraft.darkboy.ru/api/check-mod-updates/boblib.json"
    displayURL="https://minecraft.darkboy.ru/mods/boblib"
    credits="Library for Bobsans mods"
    authors="Bobsans"
    description='''Provides functionality for use in Bobsans mods'''

    [[dependencies.boblib]]
        modId="forge"
        mandatory=true
        versionRange="[40,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.boblib]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.18.2,1.19)"
        ordering="NONE"
        side="BOTH"
